### ISSUE TITLE
Include notebooks templates into JupyterLab/Elyra on ODH

### ISSUE THREAD

**Issue by pacospace** [opendatahub-io/s2i-lab-elyra#11]
**Is your feature request related to a problem? Please describe.**
Reusability of notebooks and in particular having templates with dependencies that can be reused for different steps in AI pipelines according to use case in ODH.

**Describe the solution you'd like**

1. Include notebook templates [1] in Elyra image.
2. Extend JupyterLab Extension for templates [2] that would show naming conventions and categories as discussed in [3]. 
(In the future there will be integration with GitHub directly: https://github.com/jpmorganchase/jupyterlab_templates/issues/91)
3. Add to JupyterLab Requirements extension [4] that has Thoth included so that when templates are selected, dependencies would show up for each notebook and being installed.

**Describe alternatives you've considered**

**References**
- [1] https://github.com/aicoe-aiops/data-science-workflow-examples
- [2] https://github.com/jpmorganchase/jupyterlab_templates
- [3] https://github.com/aicoe-aiops/project-template/issues/25
- [4] https://github.com/thoth-station/jupyterlab-requirements

**Additional context**
This solution could be adopted also for Jupyter notebooks on JupyterHub, started https://github.com/thoth-station/jupyter-nbtemplates

@durandom @MichaelClifford @sophwats @vpavlin @nakfour @goern @harshad16

**Comment by harshad16** [comment]
Thanks for the issue.
Going forward, this doesn't seem to fit in the roadmap of the odh notebooks 
closing the issue.
If you feel otherwise, please open the issue : [here](https://github.com/opendatahub-io/notebooks)
