### ISSUE TITLE
python interpreter version 3.8 with Elyra image

### ISSUE THREAD

**Issue by pacospace** [opendatahub-io/s2i-lab-elyra#13]
**Is your feature request related to a problem? Please describe.**
Is there plan to have new image with python 3.8 and Elyra?

**Comment by akchinSTC** [comment]
@pacospace - working on updating the image with the latest Elyra release which should be 1.5.2 . Regarding python 3.8, is there a new minimal image base from odh that I can use with this that has 3.8?

**Comment by pacospace** [comment]
> @pacospace - working on updating the image with the latest Elyra release which should be 1.5.2. Regarding python 3.8, is there a new minimal image base from odh that I can use with this that has 3.8?

@akchinSTC thank you, that sounds awesome! You can find a minimal base image for `ubi8-py38` here: https://github.com/thoth-station/s2i-thoth. Images are available on quay: https://quay.io/repository/thoth-station/s2i-thoth-ubi8-py38

**Comment by pacospace** [comment]
cc @harshad16

**Comment by harshad16** [comment]
This commit https://github.com/opendatahub-io/s2i-lab-elyra/commit/06ad875246179a9c8a8c34c795111b16a33ca21f introduces all the requirements. 
Tag [v0.0.6](https://github.com/opendatahub-io/s2i-lab-elyra/releases/tag/v0.0.6) 
Image is now available: https://quay.io/repository/thoth-station/s2i-lab-elyra?tab=tags
