### ISSUE TITLE
Input parameters for runtime-images and runtimes are not available using Elyra

### ISSUE THREAD

**Issue by pacospace** [opendatahub-io/s2i-lab-elyra#24]
**Describe the issue**
Input parameters for runtime-images and runtimes are not available when spawning Elyra in JH. 

I'm not sure why this behavior happens. I run the image [1] locally and everything works fine.

**To Reproduce**
1. Go to https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/
2. Spawn image s2i-lab-elyra:v0.0.6

**Screenshots or log output**
See: https://github.com/operate-first/support/issues/146

**Expected behavior**
All input parameters are available. Workaround currently is to use elyra cli to add runtimes and runtime-images.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.0.1
 - Operating system: ubi 8
 - Installation source: [1]
 - Deployment type: Open Data Hub v1.0.5

**References**
[1] https://quay.io/repository/thoth-station/s2i-lab-elyra?tab=tags

**Comment by pacospace** [comment]
Replicated from the one opened upstream: https://github.com/elyra-ai/elyra/issues/1473

**Comment by ptitzler** [comment]
The problem should be fixed in the next release of Elyra on ODH, which should be based on version 2.1.x (or 2.2.x).  @akchinSTC

**Comment by pacospace** [comment]
Is this issue https://github.com/opendatahub-io/s2i-lab-elyra/issues/23 stopping us from creating a new s2i-lab-elyra image with most recent Elyra version, so at least we can solve this issue for users? @ptitzler @akchinSTC ?

**Comment by ptitzler** [comment]
Yes. But as I understand it Alan can't make progress with that one because of https://github.com/opendatahub-io/odh-manifests/issues/319

**Comment by pacospace** [comment]
> Yes. But as I understand it Alan can't make progress with that one because of [opendatahub-io/odh-manifests#319](https://github.com/opendatahub-io/odh-manifests/issues/319)

Thanks @ptitzler!!

**Comment by ptitzler** [comment]
We are trying to refresh the Elyra image to v2.2.1 => https://github.com/opendatahub-io/s2i-lab-elyra/pull/26.

**Comment by pacospace** [comment]
This should be solved by https://github.com/opendatahub-io/s2i-lab-elyra/pull/26
