### ISSUE TITLE
Refresh Elyra image to version 2.2.4

### ISSUE THREAD

**Issue by ptitzler** [opendatahub-io/s2i-lab-elyra#30]
**Is your feature request related to a problem? Please describe.**
This version should include fixes for https://github.com/operate-first/support/issues/217 and https://github.com/elyra-ai/elyra/issues/1479

**Comment by ptitzler** [comment]
@akchinSTC

**Comment by akchinSTC** [comment]
@ptitzler - Probably adjust title and link PR here: https://github.com/opendatahub-io/s2i-lab-elyra/pull/33

**Comment by ptitzler** [comment]
> Probably adjust title and link PR here: #33

done

**Comment by ptitzler** [comment]
Elyra 2.2.4 is now available as an image stream https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/additional/elyra-notebook-imagestream.yaml. whenever a new manifest version is released it should include that latest version.
