### ISSUE TITLE
Minimal required Elyra extensions for integration phase 1

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/s2i-lab-elyra#37]
The following features are selected for first phase of Elyra integration:
1. Git Plugin
2. Python Script Editor
3. Python debugger 

2 can be individually selected for installation with pip package `elyra-python-editor-extension`

What about 1 and 3? Do they come as part of the `elyra[all]` package?
What other feature comes with `elyra[all]`?

**Comment by ptitzler** [comment]
> What about 1 and 3? Do they come as part of the `elyra[all]` package? 
Yes!

> What other feature comes with `elyra[all]`?

Refer to the [packaging guide for up-to-date information](https://elyra.readthedocs.io/en/latest/getting_started/installation.html#packaging). TL;DR An `elyra[all]` installation is not what one would typically chose for production deployments.

**Comment by harshad16** [comment]
With Elyra installed on the ODH workbench images directly.
This requirement is covered: https://github.com/opendatahub-io/notebooks/issues/55
Reference: https://github.com/opendatahub-io/notebooks/blob/main/jupyter/datascience/ubi9-python-3.9/Pipfile#L10-L12
Closing this issue, as it is completed.
