### ISSUE TITLE
Elyra notebook image fails to spawn in kubeflow notebook controller

### ISSUE THREAD

**Issue by bdattoma** [opendatahub-io/s2i-lab-elyra#44]
**Describe the bug**
When trying to spawn the Elyra notebook image for Jupyter from Kubeflow notebook controller, the corresponding pod gets `CrashLoopBackOff` error. 
Last rows of the pod logs: 
```
ValueError: list.remove(x): x not in list
+ exec /usr/libexec/s2i/run
ERROR: don't know how to run your application.
Please set either APP_MODULE, APP_FILE or APP_SCRIPT environment variables, or create a file 'app.py' to launch your application.
``` 

**To Reproduce**
1. Go to KFNBC spawner page
2. Select `Elyra Notebook Image` from the manu
3. Click on `Star server` button
4. Go to Pods section of cluster console
5. Search the corresponding pod of your user
6. See error

**Expected behavior**
Jupyter server is started with Elyra notebook image without issues

**Screenshots**
![image](https://user-images.githubusercontent.com/88311595/180249682-f3af088d-634b-4897-aaa3-d62bc996535c.png)

**Additional context**
-

**Comment by akchinSTC** [comment]
Will be rebuilding and rebasing the elyra image using the thoth minimal/generic image as the base image as referenced here : https://github.com/opendatahub-io/odh-manifests/issues/671#issuecomment-1234397784

Default runtime configuration information will need to be revised based on how KFP is now being deployed.

@harshad16 - any chance I can get maintainer privs for this repo to mark and edit issues as necessary?

**Comment by harshad16** [comment]
Yes surely [akchinSTC](https://github.com/akchinSTC)

**Comment by harshad16** [comment]
@LaVLaS  can you addd @akchinSTC  as a collaborator on this repo

**Comment by harshad16** [comment]
@akchinSTC opendatahub admins, have sent you invite to be a collaborator in this repo
please check your github notifications and accept it.

with regards to the issue, it seems image needed to change for it to run in kubeflow notebook controller
i m not well versed with this as of the moment, will check in what is needed to be changed.

**Comment by mamurak** [comment]
I just tried to run the fixed notebook image in Kubeflow Notebook Controller, and it still fails, unfortunately.

Using image `quay.io/thoth-station/s2i-lab-elyra:v0.2.0`, the notebook fails to start and throws this error:
```
+++ elyra-metadata install runtimes --schema_name=kfp --name=my_kfp --display_name=Default --user_namespace=redhat-ods-applications --auth_type=DEX_STATIC_PASSWORDS --api_endpoint=http://ml-pipeline.redhat-ods-applications/pipeline --api_username=user@example.com --api_password=12341234 --cos_endpoint=http://minio-service.redhat-ods-applications:9000 --cos_auth_type=USER_CREDENTIALS --cos_username= --cos_password= --cos_bucket=default --engine=Tekton
Traceback (most recent call last):
  File "/opt/app-root/bin/elyra-metadata", line 8, in <module>
    sys.exit(MetadataApp.main())
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/metadata/metadata_app.py", line 1014, in main
    elyra_metadata.start()
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/metadata/metadata_app.py", line 1033, in start
    return subinstance.start()
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/metadata/metadata_app.py", line 898, in start
    return subinstance.start()
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/metadata/metadata_app.py", line 466, in start
    super().start()  # process options
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/metadata/metadata_app.py", line 60, in start
    self.process_cli_options(self.options)
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/metadata/metadata_app_utils.py", line 590, in process_cli_options
    self.process_cli_option(option)
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/metadata/metadata_app_utils.py", line 567, in process_cli_option
    self._remove_argv_entry(option)
  File "/opt/app-root/lib64/python3.8/site-packages/elyra/metadata/metadata_app_utils.py", line 628, in _remove_argv_entry
    self.argv.remove(entry)
ValueError: list.remove(x): x not in list
```

It's the same error that was reported in this issue originally.

**Comment by akchinSTC** [comment]
@mamurak - can you provide me a little more info?
1. openshift version
2. odh operator version
3. link to kfdef if possible

**Comment by mamurak** [comment]
@akchinSTC I'm using

1. OpenShift 4.10
2. ODH operator 1.4.0
3. the following kfdef spec

```
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        overlays:
          - authentication
        repoRef:
          name: manifests
          path: odh-dashboard
      name: odh-dashboard
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-notebook-controller
      name: odh-notebook-controller
    - kustomizeConfig:
        overlays:
          - metadata-store-mariadb
          - ds-pipeline-ui
          - object-store-minio
          - default-configs
        repoRef:
          name: manifests
          path: data-science-pipelines
      name: ds-pipelines
    - kustomizeConfig:
        overlays:
          - additional
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
  repos:
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v1.4'
```

**Comment by akchinSTC** [comment]
@mamurak - I was able to reproduce, ive pushed a fix for issue in a new PR. in the meantime, if needed, Ive also pushed a new image with the changes for you to use : quay.io/akchinstc/elyra-notebook:v3.12.0

**Comment by harshad16** [comment]
With Elyra installed on the ODH workbench images directly.
This requirement is covered: https://github.com/opendatahub-io/notebooks/issues/55
Reference: https://github.com/opendatahub-io/notebooks/releases/tag/v1.4.0
Please refer ODH base notebook images, to utilize elyra.
Closing this issue, as it is completed.
