### ISSUE TITLE
Latest release is installing incorrect version of Elyra

### ISSUE THREAD

**Issue by akchinSTC** [opendatahub-io/s2i-lab-elyra#45]
**Describe the bug**
See Pull Request : https://github.com/opendatahub-io/s2i-lab-elyra/pull/43

After updating all the relevant sections, manifests, lock files, the container still contains the previous version of Elyra(3.9.1) instead of the latest 3.10.1.

**To Reproduce**
1. Run `podman run -it quay.io/thoth-station/s2i-lab-elyra:v0.1.5 /bin/bash`
2. then `python3 -m pip list installed | grep elyra`
3. See error

**Expected behavior**
The build system should install the latest version of elyra specified. (3.10.1)

**Screenshots**
![image](https://user-images.githubusercontent.com/13340013/182919872-064e1afa-cf02-4a82-9825-c0c1a6b28d18.png)

**Additional context**

**Comment by akchinSTC** [comment]
@harshad16 - Hi, we're having slight problem with getting the latest version of elyra installed. Everything looks correct but the image built still contains the previous version.

**Comment by harshad16** [comment]
Thank you for pointing it out 
we rescheduled the build, the issue is now fixed.
```
 podman run -it quay.io/thoth-station/s2i-lab-elyra:v0.1.5 bash
(app-root) pip show elyra
Name: elyra
Version: 3.10.1
Summary: Elyra provides AI Centric extensions to JupyterLab
Home-page: https://github.com/elyra-ai/elyra
Author: Elyra Maintainers
Author-email: 
License: Apache License Version 2.0
Location: /opt/app-root/lib/python3.8/site-packages
Requires: autopep8, black, click, colorama, deprecation, entrypoints, jinja2, jsonschema, jupyter-client, jupyter-core, jupyter-packaging, jupyter-resource-usage, jupyter-server, jupyterlab, jupyterlab-git, jupyterlab-lsp, kfp, MarkupSafe, minio, nbclient, nbconvert, nbdime, nbformat, networkx, papermill, pygithub, python-lsp-server, pyyaml, requests, rfc3986-validator, tornado, traitlets, typing-extensions, urllib3, watchdog, websocket-client, yaspin
Required-
```

@akchinSTC  can you retest and close the issue if you feel its fixed.
thank you :)

**Comment by akchinSTC** [comment]
Checked and verified its 3.10.1. Thanks for the quick turnaround @harshad16 !
