### ISSUE TITLE
Invalid KF_DEPLOYMENT_NAMESPACE from env grep

### ISSUE THREAD

**Issue by MightyNerdEric** [opendatahub-io/s2i-lab-elyra#53]
**Describe the bug**
When launching a notebook using the v0.2.0 or v0.2.1 image, we get an error due to a bad value in `KF_DEPLOYMENT_NAMESPACE`. This is due to the fact that both `JUPYTER_IMAGE` and `JUPYTER_IMAGE_SPEC` are defined in the env, so the grep/cut [here](https://github.com/opendatahub-io/s2i-lab-elyra/blob/f811bf1e3056bb4b011eb3a64c7d59e07f14700c/setup-elyra.sh#L17) returns two matching results with a newline between them.
Error looks like this (actual image name replaced with <imagename> for clarity):
`Validation failed for instance 'my_kfp' using the kfp schema with error: 'http://ml-pipeline.<imagename>\n<imagename>/pipeline' is not a 'uri'.`

**To Reproduce**
1. Launch a new Elyra notebook from v0.2.0 or v0.2.1 image on a Jupyterhub instance that defines both JUPYTER_IMAGE and JUPYTER_IMAGE_SPEC env vars.
2. This will fail. Logs can be inspected to see the error.

**Expected behavior**
A single line is used for the `KF_DEPLOYMENT_NAMESPACE`. This could be achieved in several ways. I believe `JUPYTER_IMAGE` and `JUPYTER_IMAGE_SPEC` should always match, so the grep could simply have the `-m1` param added so that it only returns the first result.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by akchinSTC** [comment]
@MightyNerdEric - Thanks for the bug report. The grep was not my ideal solution but did the job. PR open for the quick fix. Moving fwd will see about injecting/plumbing in a dedicated env var for the namespace

**Comment by harshad16** [comment]
With Elyra installed on the ODH workbench images directly.
Please refer ODH base notebook images, to utilize elyra.

Closing this issue. Feel free to open the issue on 
Reference: https://github.com/opendatahub-io/notebooks
