### ISSUE TITLE
Remove system-owned runtime image configurations

### ISSUE THREAD

**Issue by ptitzler** [opendatahub-io/s2i-lab-elyra#58]
**Is your feature request related to a problem? Please describe.**
Elyra installations include a set of preconfigured [runtime image configurations](https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html), which don't work on OpenShift. We should remove these default configurations.

**Describe the solution you'd like**
Remove the default configurations. This can be done in the `Dockerfile` [after the requirements were installed](https://github.com/opendatahub-io/s2i-lab-elyra/blob/master/Dockerfile#L12).

Edit:

After `pip install elyra` has completed, the default runtime image configuration files are located in one of the Jupyter data directories. For example

```
$ jupyter --paths
config:
   ...
data:
    /opt/anaconda3/envs/upstream/share/jupyter
    /Users/patti/Library/Jupyter
    /Users/patti/.local/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    ...

$ ls /opt/anaconda3/envs/upstream/share/jupyter/metadata/runtime-images
anaconda.json			pytorch-runtime.json		tensorflow_2x_py3.json
pandas.json			r.json
pytorch-devel.json		tensorflow_2x_gpu_py3.json
```

Support for default runtime image configurations will be disabled/removed in a future Elyra release. To add a custom set of image configurations as default after installation, one can run the [`elyra-metadata create` CLI command](https://elyra.readthedocs.io/en/latest/user_guide/runtime-image-conf.html#adding-a-runtime-configuration) , like it is already done for runtime configurations here https://github.com/opendatahub-io/s2i-lab-elyra/blob/master/setup-elyra.sh#L22.

**Comment by guimou** [comment]
Those changes will be made in the new lines of images here: https://github.com/opendatahub-io/notebooks

**Comment by harshad16** [comment]
With Elyra installed on the ODH workbench images directly.
Please refer ODH base notebook images, to utilize elyra.

Closing this issue. Feel free to open the issue on 
Reference: https://github.com/opendatahub-io/notebooks
