### ISSUE TITLE
Pin kfp-tekton dependency to match installed Tekton version

### ISSUE THREAD

**Issue by ptitzler** [opendatahub-io/s2i-lab-elyra#59]
**Describe the bug**

Elyra uses the [`kfp-tekton`](https://github.com/kubeflow/kfp-tekton) package to communicate with Kubeflow Pipelines. Elyra currently installs this package as a dependency but does not impose any version constraints. [Version 1.6 of that package introduces a breaking change](https://github.com/kubeflow/kfp-tekton/releases/tag/v1.6.0), which renders it (and later versions) unusable for Tekton version < 0.44. We therefore need to pin `kfp-tekton` to a version that is compatible with the version of Tekton that's deployed on Open Data Hub:

- Tekton >= 0.44 -> `kfp-tekton` 1.6+
- Tekton < 0.44 -> `kfp-tekton` 1.5.x

**Comment by HumairAK** [comment]
@harshad16 / @rimolive  fyi

**Comment by ptitzler** [comment]
In the next release we are [lowering the floor back to version 1.5.2](https://github.com/elyra-ai/elyra/blob/main/pyproject.toml#L89), but won't impose a ceiling. This enables us to theoretically support every version of Tekton that `kf-tekton` (>=1.5.2) supports. That means:
- Standard deployments (e.g. `pip install elyra[kfp-tekton]`) will install the most recent version of the `kfp-tekton`  package (1.6.x as of now) and thus require Tekton >= 0.44.
- To use an older version of Tekton, the appropriate version of `kfp-tekton` must be installed manually, i.e
   ```
   $ pip install "kfp-tekton<1.6.0"
   $ pip install elyra
   ```

**Comment by harshad16** [comment]
Ack, we would be able to introduce the kfp-tekton pinning in notebook images.
thanks, this helps.

**Comment by harshad16** [comment]
With Elyra installed on the ODH workbench images directly.
Please refer ODH base notebook images, to utilize elyra.
This requirement is already fixed there with: https://github.com/opendatahub-io/notebooks/pull/58

Closing this issue as completed.
