### ISSUE TITLE
Hide runtimes other than Kubeflow Pipelines

### ISSUE THREAD

**Issue by ptitzler** [opendatahub-io/s2i-lab-elyra#60]
**Is your feature request related to a problem? Please describe.**
The Elyra container image currently exposes three runtimes (local execution, Kubeflow Pipelines, and Apache Airflow) to the end-user. Once https://github.com/elyra-ai/elyra/pull/3114 is generally available, it is possible to selectively enable runtimes. The necessary steps are documented in https://elyra.readthedocs.io/en/latest/user_guide/pipeline-editor-configuration.html#enabling-specific-runtimes

**Describe the solution you'd like**
Update the container image to only enable Kubeflow Pipelines in the JupyterLab UI.

**Comment by harshad16** [comment]
With Elyra installed on the ODH workbench images directly.
Please refer ODH base notebook images, to utilize elyra.
This requirement is already fixed there with: https://github.com/opendatahub-io/notebooks/pull/58

Closing this issue as completed.
