### ISSUE TITLE
s2i-lab-elyra v0.0.4 stucks in the web browser

### ISSUE THREAD

**Issue by harshad16** [opendatahub-io/s2i-lab-elyra#9]
**Describe the bug**
while trying to use the s2i-lab-elyra version v0.0.4, noticed is being stuck as soon as it opens on web browser, becomes unresponsive in some time.
used the following command to test it out: 
`podman run -it -p 8888:8888 quay.io/thoth-station/s2i-lab-elyra:v0.0.4 jupyter lab`

contrast to the elyra image frm elyra-ai, it doesn't stuck on opening.
`podman run -it -p 8888:8888 elyra/elyra jupyter lab`

**To Reproduce**
1. Execute `podman run -it -p 8888:8888 quay.io/thoth-station/s2i-lab-elyra:v0.0.4 jupyter lab`
2. See error

**Comment by vpavlin** [comment]
I have not experienced anything like this in JupyterHub

**Comment by vpavlin** [comment]
I tried your reproducet and it started without any issues
![Uploading Screenshot from 2020-10-22 14-56-20.png…]()

**Comment by vpavlin** [comment]
I tried your reproducer locally and something seems to be eating a lot of resources, so JupyterLab works, but is very very slow (whole machine slowed down).

**Comment by akchinSTC** [comment]
@vpavlin @harshad16 - could you give me the details of how you were able to recreate the issue. wondering if this can be recreated using podman-machine locally

**Comment by vpavlin** [comment]
I think @harshad16 described it well in the top comment - just run it, access the UI via browser and you should see things getting stuck

**Comment by martinpovolny** [comment]
I have the very same experience as of today. Tried FF, Chrome and Opera. Different versions.

**Comment by martinpovolny** [comment]
Seems to be still the issue with 0.0.5 (trying to follow https://github.com/thoth-station/elyra-aidevsecops-tutorial)

**Comment by pacospace** [comment]
Is this still available in v0.0.7?

**Comment by harshad16** [comment]
> Is this still available in v0.0.7?

good question.
Test the v0.0.7 locally and it works flawlessly for me :) 
closing the issue. if anyone faces the same issue, please open a new issue.
